using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Diagnostics;
using System.IO;

namespace Group16SE.Frontend.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly IWebHostEnvironment hostEnvironment;

        public ValuesController(IWebHostEnvironment webHostEnvironment)
        {
            hostEnvironment = webHostEnvironment;
        }

        // GET: api/<ValuesController>
        [HttpGet]
        public string Get()
        {
            ProcessStartInfo start = new ProcessStartInfo
            {
                FileName = Path.Combine(hostEnvironment.ContentRootPath, "python364x64/python.exe"),
                // Argument with file name and input parameters
                Arguments = string.Format("{0} {1}", Path.Combine(hostEnvironment.ContentRootPath, "Python/JsonReader.py"), Path.Combine(hostEnvironment.ContentRootPath, "current_assignment.json")),
                UseShellExecute = false,
                CreateNoWindow = true,
                // Any output, generated by application will be redirected back
                RedirectStandardOutput = true,
                // Any error in standard output will be redirected back (for example exceptions)
                RedirectStandardError = true,
                // Runs process elevated
                // THIS PROPERTY IS VITAL FOR THE PROCESS TO RUN ON THE AZURE APP SERVICE
                // Doesn't matter when running locally (or in development environment maybe?)
                Verb = "runas"
            };
            using Process process = Process.Start(start);
            using StreamReader reader = process.StandardOutput;
            string stderr = process.StandardError.ReadToEnd();
            string result = reader.ReadToEnd();
            return ($"{result}");
        }
    }
}
